Type: AWS::ElasticBeanstalk::ConfigurationTemplate
Properties:
    ApplicationName:
        Ref: openTokenApplication
    Description: OpenToken.io Configuration Template
    OptionSettings:
        -
            Namespace: aws:autoscaling:asg
            OptionName: MinSize
            Value: 1
        -
            Namespace: aws:autoscaling:asg
            OptionName: MaxSize
            Value: 2
        -
            Namespace: aws:elasticbeanstalk:environment
            OptionName: EnvironmentType
            Value: LoadBalanced
    SolutionStackName: 64bit Amazon Linux 2015.09 v2.0.8 running Node.js
